apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmctld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmctld
  template:
    metadata:
      labels:
        app: slurmctld
    spec:
      containers:
      - name: slurmctld
        image: gromr1/slurmctld
        env:
        - name: SLURM_CLUSTER_NAME
          value: "K8s-cluster"
        - name: SLURM_CONTROL_MACHINE
          value: "slurmctld"
        - name: SLURM_NODE_NAMES
          value: "slurmd"
        - name: INFLUXDB_HOST
          value: "influxdb"
        - name: INFLUXDB_DATABASE_NAME
          value: "docker_slurm"
      hostname: slurmctld

